# Numpy and Pandas

## Numpy

In [3]:
# numpy => Numerical Python is a python library used for numerical computing
# python is slow
# numpy is fast as it's written in C
# helps in handling large scale numerical operations

In [4]:
import numpy as np

In [9]:
my_list = [1, 2, 3, 4]
my_list = my_list * 2
my_list #duplicates the list

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
array = np.array([1, 2, 3, 4])
# type(array)
array *= 2 #doubles the array numbers unlike the python list
array

array([2, 4, 6, 8])

### Multi Dimensional Arrays Numpy

In [43]:
array1 = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]]) 
array2 = np.array([[[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], 
                  
                  [[1, 2, 3], 
                   [1, 5, 3], 
                   [1, 2, 3]]]) 
#like matrices

print(array1.ndim)
print(array2.ndim)

print(array1.shape) #(Number of Rows, Number of Columns)
print(array2.shape) #(Number of Arrays, Number of Rows, Number of columns)

2
3
(3, 3)
(2, 3, 3)


In [44]:
print(array2[0][0][0]) #python's chain indexing

1


In [45]:
array2[1, 1, 1] #numpy's multi dimensional indexing (faster than python's chain indexing)

np.int64(5)

In [47]:
word = str(array2[0, 0, 0]) + str(array2[1, 1, 1]) + str(array2[1, 1, 2])
word

'153'

### Slicing

In [70]:
array = np.array([[1, 2, 3 ,4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

In [195]:
#Row Slicing

# array[start:end:step]
# ending index is exclusive
# array[0:3] #from index 0 to 2 
# array[:] #everthing will be show
# array[::2] #0, 2 steps of 2 i.e. 0 to 2 to 4 to 6
array[::-3] # reverse and steps of 3

array([[13, 14, 15, 16],
       [ 1,  2,  3,  4]])

In [184]:
#Row + Column Slicing
# array[row => startRow:endRow:step, column => startCol:endCol:step]
array[:, 2] #[: => all rows, of column 0]
array[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [213]:
array[2::, 2::]

array([[11, 12],
       [15, 16]])

### Arithmetic

In [235]:
#Scaler Arithmetic

array = np.array([1, 2 ,3])

print(array + 1)
print(array - 1)
print(array * 2)
print(array / 2)
print(array ** 5)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[  1  32 243]


In [241]:
# Vectorized Math Functions

array2 = np.array([1.01, 2.5, 3.99])

print(np.sqrt(array2))
print(np.round(array2))
print(np.pi)
print(np.e)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
3.141592653589793
2.718281828459045


In [243]:
radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [247]:
# Element-wise Arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [254]:
# Comparison Operators

scores = np.array([91, 55, 100, 73, 82, 64])

scores[scores < 60] = 0
scores

array([ 91,   0, 100,  73,  82,  64])

### Broadcasting

In [267]:
# Broadcasting allows NumPy to perform operations on arrays 
# with different shapes by visually expanding dimensions
# so that they match the larger array's shape

# The dimensions have the same size
# Or
# One of the dimensions has a size of 1

# ✅
# (2, 1) 
# (1, 2) 

# ❌
# (2, 3)
# (3, 2)

In [269]:
array1 = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1], 
                   [2], 
                   [3], 
                   [4]])

print(array1.shape)
print(array2.shape)

(4, 4)
(4, 1)


In [270]:
newArr = (array1 * array2)
newArr

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36],
       [52, 56, 60, 64]])

In [281]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Aggregate Functions

In [282]:
# Aggregate functions => summarize data and typically return a single value

In [299]:
array = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10]])

print(np.sum(array))
print(np.mean(array))
print(np.var(array)) # variance
print(np.std(array)) # standard deviation
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array, axis = 0)) # axis => 1 is row, axis => 0 is column
print(np.sum(array, axis = 1)) # axis => 1 is row, axis => 0 is column

55
5.5
8.25
2.8722813232690143
1
10
0
9
[ 7  9 11 13 15]
[15 40]


### Filtering

In [300]:
# Filtering =>refers to the process of selecting elements from an array
# that match a given condition

In [325]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

#using boolean indexing
teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages <= 55)] #since numpy uses C under the hood, using ampersand(&) instead of (and)
boomers = ages[ages > 55]
evenAges = ages[ages % 2 == 0]
oddAges = ages[ages % 2 != 0]

# using where funtion/clause mostly only required for preserving the shape of the array/data
threeMultipleAges = np.where(ages % 3 == 0 , ages, 0) #but it's slower than boolean indexing
# np.where(condition, array, fill value => what to fill the False condition array items)

print(ages)
print(teenagers)
print(adults)
print(boomers)
print(evenAges)
print(oddAges)

print(threeMultipleAges)

[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]
[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[[21  0  0  0  0 30 18  0]
 [39  0 15 99 18  0  0 21]]


### Random Numbers

In [395]:
rng = np.random.default_rng()

print(rng.integers(low = 1, high = 8, size = (3, 2))) # low, high => keyword argument (optional)

[[2 5]
 [1 7]
 [2 2]]


In [404]:
rng = np.random.default_rng(seed = 1) # seed is used to retain the same random elements
# if you need the reproduction of the same number then use seed.

random_array = rng.integers(low = 30, high = 90, size = (2, 3))

print(random_array)

[[58 60 75]
 [87 32 38]]


In [420]:
np.random.seed(seed = 1)

floatingPointNums = np.random.uniform(low = 9, high = 20, size = (2,2))

floatingPointNums

array([[13.58724205, 16.92356943],
       [ 9.00125812, 12.3256583 ]])

In [464]:
#shuffling arrays
rng = np.random.default_rng(seed = 12)

array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)

array

array([2, 3, 4, 5, 1])

In [483]:
#selecting random element/choice

fruits = np.array(["🍎", "🍌", "🍓", "🥝", "🍉"])
fruits = rng.choice(fruits, size = (3, 4))
print(fruits)

[['🍎' '🥝' '🍌' '🍉']
 ['🥝' '🍉' '🍎' '🍌']
 ['🍉' '🍉' '🍉' '🥝']]
