# Numpy and Pandas

## Numpy

In [5]:
# numpy => Numerical Python is a python library used for numerical computing
# python is slow
# numpy is fast as it's written in C
# helps in handling large scale numerical operations

In [6]:
import numpy as np

In [7]:
my_list = [1, 2, 3, 4]
my_list = my_list * 2
my_list #duplicates the list

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
array = np.array([1, 2, 3, 4])
# type(array)
array *= 2 #doubles the array numbers unlike the python list
array

array([2, 4, 6, 8])

### Multi Dimensional Arrays Numpy

In [9]:
array1 = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]]) 
array2 = np.array([[[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], 
                  
                  [[1, 2, 3], 
                   [1, 5, 3], 
                   [1, 2, 3]]]) 
#like matrices

print(array1.ndim)
print(array2.ndim)

print(array1.shape) #(Number of Rows, Number of Columns)
print(array2.shape) #(Number of Arrays, Number of Rows, Number of columns)

2
3
(3, 3)
(2, 3, 3)


In [10]:
print(array2[0][0][0]) #python's chain indexing

1


In [11]:
array2[1, 1, 1] #numpy's multi dimensional indexing (faster than python's chain indexing)

np.int64(5)

In [12]:
word = str(array2[0, 0, 0]) + str(array2[1, 1, 1]) + str(array2[1, 1, 2])
word

'153'

### Slicing

In [13]:
array = np.array([[1, 2, 3 ,4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

In [14]:
#Row Slicing

# array[start:end:step]
# ending index is exclusive
# array[0:3] #from index 0 to 2 
# array[:] #everthing will be show
# array[::2] #0, 2 steps of 2 i.e. 0 to 2 to 4 to 6
array[::-3] # reverse and steps of 3

array([[13, 14, 15, 16],
       [ 1,  2,  3,  4]])

In [15]:
#Row + Column Slicing
# array[row => startRow:endRow:step, column => startCol:endCol:step]
array[:, 2] #[: => all rows, of column 0]
array[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [16]:
array[2::, 2::]

array([[11, 12],
       [15, 16]])

### Arithmetic

In [17]:
#Scaler Arithmetic

array = np.array([1, 2 ,3])

print(array + 1)
print(array - 1)
print(array * 2)
print(array / 2)
print(array ** 5)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[  1  32 243]


In [18]:
# Vectorized Math Functions

array2 = np.array([1.01, 2.5, 3.99])

print(np.sqrt(array2))
print(np.round(array2))
print(np.pi)
print(np.e)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
3.141592653589793
2.718281828459045


In [19]:
radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [20]:
# Element-wise Arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [21]:
# Comparison Operators

scores = np.array([91, 55, 100, 73, 82, 64])

scores[scores < 60] = 0
scores

array([ 91,   0, 100,  73,  82,  64])

### Broadcasting

In [22]:
# Broadcasting allows NumPy to perform operations on arrays 
# with different shapes by visually expanding dimensions
# so that they match the larger array's shape

# The dimensions have the same size
# Or
# One of the dimensions has a size of 1

# ✅
# (2, 1) 
# (1, 2) 

# ❌
# (2, 3)
# (3, 2)

In [23]:
array1 = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1], 
                   [2], 
                   [3], 
                   [4]])

print(array1.shape)
print(array2.shape)

(4, 4)
(4, 1)


In [24]:
newArr = (array1 * array2)
newArr

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36],
       [52, 56, 60, 64]])

In [25]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Aggregate Functions

In [26]:
# Aggregate functions => summarize data and typically return a single value

In [27]:
array = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10]])

print(np.sum(array))
print(np.mean(array))
print(np.var(array)) # variance
print(np.std(array)) # standard deviation
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array, axis = 0)) # axis => 1 is row, axis => 0 is column
print(np.sum(array, axis = 1)) # axis => 1 is row, axis => 0 is column

55
5.5
8.25
2.8722813232690143
1
10
0
9
[ 7  9 11 13 15]
[15 40]


### Filtering

In [28]:
# Filtering =>refers to the process of selecting elements from an array
# that match a given condition

In [29]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

#using boolean indexing
teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages <= 55)] #since numpy uses C under the hood, using ampersand(&) instead of (and)
boomers = ages[ages > 55]
evenAges = ages[ages % 2 == 0]
oddAges = ages[ages % 2 != 0]

# using where funtion/clause mostly only required for preserving the shape of the array/data
threeMultipleAges = np.where(ages % 3 == 0 , ages, 0) #but it's slower than boolean indexing
# np.where(condition, array, fill value => what to fill the False condition array items)

print(ages)
print(teenagers)
print(adults)
print(boomers)
print(evenAges)
print(oddAges)

print(threeMultipleAges)

[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]
[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[[21  0  0  0  0 30 18  0]
 [39  0 15 99 18  0  0 21]]


### Random Numbers

In [30]:
rng = np.random.default_rng()

print(rng.integers(low = 1, high = 8, size = (3, 2))) # low, high => keyword argument (optional)

[[7 1]
 [3 1]
 [4 6]]


In [31]:
rng = np.random.default_rng(seed = 1) # seed is used to retain the same random elements
# if you need the reproduction of the same number then use seed.

random_array = rng.integers(low = 30, high = 90, size = (2, 3))

print(random_array)

[[58 60 75]
 [87 32 38]]


In [32]:
np.random.seed(seed = 1)

floatingPointNums = np.random.uniform(low = 9, high = 20, size = (2,2))

floatingPointNums

array([[13.58724205, 16.92356943],
       [ 9.00125812, 12.3256583 ]])

In [33]:
#shuffling arrays
rng = np.random.default_rng(seed = 12)

array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)

array

array([2, 3, 4, 5, 1])

In [34]:
#selecting random element/choice

fruits = np.array(["🍎", "🍌", "🍓", "🥝", "🍉"])
fruits = rng.choice(fruits, size = (3, 4))
print(fruits)

[['🍎' '🍎' '🍎' '🍎']
 ['🍓' '🍌' '🍓' '🍌']
 ['🍉' '🥝' '🥝' '🍎']]


### Practice

In [39]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
threeByThree = np.zeros(dtype = int, shape=(3, 3))
print(threeByThree)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [50]:
fourByFour = np.ones(dtype=int, shape = (4, 4))
print(fourByFour)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [53]:
identityMat = np.identity(dtype=int, n = 3)
print(identityMat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [65]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 * array2)
print(np.dot(array1, array2))

[5 7 9]
[ 4 10 18]
32


In [74]:
arrayOfMychoice = np.array([[1, 2, 3, 4], 
                            [5, 6, 7, 8]])

print(arrayOfMychoice.shape)
print(arrayOfMychoice.size)
print(arrayOfMychoice.ndim)
print(arrayOfMychoice.dtype)

(2, 4)
8
2
int64


In [78]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])
print(arr[3::])
print(arr[::-1])

30
[40 50]
[50 40 30 20 10]


In [90]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array = array.reshape((3, 4))
print(array)

array = array.flatten()
print(array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [134]:
rng = np.random.default_rng(seed = 2006)

arrayInt = rng.integers(low = 0, high = 5, size=(3, 4))
arrayFloat = np.random.uniform(low=0, high=10, size=(2, 4))

print(array.min())
print(array.max())

print(arrayFloat)

1
4
[[3.96767474 5.38816734 4.19194514 6.852195  ]
 [2.0445225  8.78117436 0.27387593 6.7046751 ]]


In [144]:
arr = np.array([1, 5, 8, 12, 15])

print(arr[arr > 7])

[ 8 12 15]


In [118]:
print(arrayInt)

print(arrayInt.mean(axis=0))
print(arrayInt.mean(axis=1))

print(arrayInt.std())
print(arrayInt.var())

[[2 4 0 1]
 [0 4 0 4]
 [2 0 2 0]]
[1.33333333 2.66666667 0.66666667 1.66666667]
[1.75 2.   1.  ]
1.6051133570215186
2.576388888888889


In [ ]:

array1 = rng.integers(low = 0, high = 10, size = (2, 2))
array2 = rng.integers(low = 0, high = 10, size = (2, 2))

print(array1)
print(array2)


print(np.matmul(array1, array2))
determinant = np.linalg.det(array1)

if(np.isclose(determinant, 0) != 0): #determinant may not directly equal to 0 due to floating point numbers so it's better to use isclose method
    print(f"Determinant: {determinant:.2f}")
    print(np.linalg.inv(array1))


[[2 4]
 [0 6]]
[[3 4]
 [1 7]]
[[10 36]
 [ 6 42]]


In [178]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
uniqueArr = np.unique(arr)

sorted_array = np.sort(uniqueArr)

print(uniqueArr)

print(sorted_array[::-1]) #in descending

[1 2 3 4 5]
[5 4 3 2 1]


In [152]:
arr = np.array([10,15,20,25,30])

greaterThan20 = np.where(arr < 20, arr, 0)

print(arr)
print(greaterThan20)

[10 15 20 25 30]
[10 15  0  0  0]


In [161]:
fiveByFive = rng.integers(high=101, low = 1, size = (5, 5))

print(fiveByFive)

newArray = np.where(fiveByFive % 2 != 0, fiveByFive, -1)

print(newArray)

fiveByFive.sum(axis=1)

[[21 36 89 38 97]
 [38 18  9  6  6]
 [39  2 78 96 14]
 [55  6 56 67 34]
 [70 26  1 80 85]]
[[21 -1 89 -1 97]
 [-1 -1  9 -1 -1]
 [39 -1 -1 -1 -1]
 [55 -1 -1 67 -1]
 [-1 -1  1 -1 85]]


array([281,  77, 229, 218, 262])

In [169]:
array = rng.integers(low = 0, high = 9, size = (2, 3))

print(array + 10) #adding 10 to each element of the array

multiArr = np.array([[1, 2, 3]])

print(array.shape)
print(multiArr.shape)

print(array)
print(array * multiArr) #multiplying each row of 2 * 3 array by [1, 2, 3]


[[18 17 15]
 [13 14 14]]
(2, 3)
(1, 3)
[[8 7 5]
 [3 4 4]]
[[ 8 14 15]
 [ 3  8 12]]


In [173]:
arrayA = np.array([[1, 2], 
                   [3, 4]])

arrayB = np.array([[5, 6], 
                   [7, 8]])

print(np.vstack((arrayA, arrayB)))
print(np.hstack((arrayA, arrayB)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Pandas

In [9]:
# pandas => python library built on top of numpy
# Used in machine learning, data analysis, data science
# name comes froms "Panal data"

# objects of pandas => Series and Dataframe

# Series => 1D Labelled table column
# Dataframe => 2D Labelled table or grid

In [1]:
import pandas as pd

### Series

In [4]:
# Series => Labeled array that can hold any type of data
# It's like a single column in an excel spreadsheet (1 - Dimensional)

In [63]:
data = [100, 102, 104, 200, 202]

series = pd.Series(data, index = ["a", "b", "c", "d", "e"]) #Series() is a constructor

# series.loc["c"] = 500

print(series.loc["c"]) # loc => location by label
print(series.iloc[0])  # iloc => location by integer or integer location

104
100


In [40]:
print(series[series >= 200])

d    200
e    202
dtype: int64


In [57]:
calories = {"Day 1": 1750, "Day 2": 2100, "Day 3": 1700}

series = pd.Series(calories) # no need of the "index" keyword argument

print(series[series < 2000])
print(series[series >= 2000])

Day 1    1750
Day 3    1700
dtype: int64
Day 2    2100
dtype: int64


In [61]:
chelseaPlaying11 = ["Sanchez", "James", "Fofana", "Sarr", "Hato", "Santos", "Caicedo", "Neto", "Estevao", "Garnacho", "Delap"]

chelseaPlayersSeries = pd.Series(chelseaPlaying11, index=[i for i in range(1, 12)])

print(chelseaPlayersSeries)

1      Sanchez
2        James
3       Fofana
4         Sarr
5         Hato
6       Santos
7      Caicedo
8         Neto
9      Estevao
10    Garnacho
11       Delap
dtype: str


### DataFrames

In [62]:
# DataFrame => tabular data structure with rows and columns. (2 Dimensional)
# Similar to an Excel spreadsheet

In [108]:
data = {"Name": ['John', 'Spongebob', "Patrick", "Sandy"], 
        "Age": ['55', '30', '35', '29']
        }

df = pd.DataFrame(data, index = ["Employee 1", "Employee 2", "Employee 3", "Employee 4"]) #DataFrame() is a constructer

print(df.loc["Employee 1"])
print(df.iloc[0]) # loc means location as per label

Name    John
Age       55
Name: Employee 1, dtype: str
Name    John
Age       55
Name: Employee 1, dtype: str


In [109]:
# add a new column

df['Job'] = ["Cleaner", "Chef", "Security Guard", "Waitress"]

print(df)

                 Name Age             Job
Employee 1       John  55         Cleaner
Employee 2  Spongebob  30            Chef
Employee 3    Patrick  35  Security Guard
Employee 4      Sandy  29        Waitress


In [ ]:
# add a new row
new_rows = pd.DataFrame([{"Name": "Squidward", "Age": "60", "Job": "Cashier"}, 
                         {"Name": "Tom", "Age": "48", "Job": "Police"}], 
                         index = ["Employee 5", "Employee 6"])

df = pd.concat([df, new_rows]) 

print(df)

                 Name Age             Job
Employee 1       John  55         Cleaner
Employee 2  Spongebob  30            Chef
Employee 3    Patrick  35  Security Guard
Employee 4      Sandy  29        Waitress
Employee 5  Squidward  60         Cashier
Employee 6        Tom  48          Police


In [116]:
chelsea_dict = {"Name": ["Palmer", "Enzo", "Caicedo", "James"], 
                "OVR": [90, 89, 92, 90]}

chelsea_df = pd.DataFrame(chelsea_dict, index = [i for i in range (1, 5)])

add_chelsea_df = pd.DataFrame([{"Name": "Cucurella", "OVR": 89}], index = [5])

chelsea_df = pd.concat([chelsea_df, add_chelsea_df])

print(chelsea_df)

        Name  OVR
1     Palmer   90
2       Enzo   89
3    Caicedo   92
4      James   90
5  Cucurella   89


### Importing and Selection

In [46]:
#importing

df = pd.read_csv("data/pokemon.csv", index_col = "Name")

# df = pd.read_json("data/smth.json")
# df = pd.read_excel("data/smth.xlsx")

print(df)

             No    Type1   Type2  Height  Weight  Legendary
Name                                                       
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]


In [48]:
# Selection by Column

# print(df["Name"])
# print(df["Height"])

print(df[["Height", "Weight"]])

            Height  Weight
Name                      
Bulbasaur      0.7     6.9
Ivysaur        1.0    13.0
Venusaur       2.0   100.0
Charmander     0.6     8.5
Charmeleon     1.1    19.0
...            ...     ...
Moltres        2.0    60.0
Dratini        1.8     3.3
Dragonair      4.0    16.5
Dragonite      2.2   210.0
Mewtwo         2.0   122.0

[150 rows x 2 columns]


In [61]:
# Selection by Row

print(df.loc["Charizard":"Blastoise", ["Height", "Weight"]])

           Height  Weight
Name                     
Charizard     1.7    90.5
Squirtle      0.5     9.0
Wartortle     1.0    22.5
Blastoise     1.6    85.5


In [67]:
df.head(10)

,No,Type1,Type2,Height,Weight,Legendary
Name,,,,,,
Bulbasaur,1,Grass,Poison,0.7,6.9,0
Ivysaur,2,Grass,Poison,1.0,13.0,0
Venusaur,3,Grass,Poison,2.0,100.0,0
Charmander,4,Fire,NaN,0.6,8.5,0
Charmeleon,5,Fire,NaN,1.1,19.0,0
Charizard,6,Fire,Flying,1.7,90.5,0
Squirtle,7,Water,NaN,0.5,9.0,0
Wartortle,8,Water,NaN,1.0,22.5,0
Blastoise,9,Water,NaN,1.6,85.5,0


In [84]:
print(df.iloc[0:11:2, :3:]) #slicing like in numpy array
#iloc[row_slicing, column_slicing]

            No  Type1   Type2
Name                         
Bulbasaur    1  Grass  Poison
Venusaur     3  Grass  Poison
Charmeleon   5   Fire     NaN
Squirtle     7  Water     NaN
Blastoise    9  Water     NaN
Metapod     11    Bug     NaN


In [ ]:
pokemon_name = input("Your Pokemon: ")

try:   
    print(df.loc[pokemon_name.capitalize()])

except KeyError:
    print("Your Pokemon Doesn't exist (Potentially New)")


Your Pokemon Doesn't exist (Potentially New)
