## Regression

## Importing Essential Packages

In [1]:
import numpy as np
import pandas as pd

## Linear Regression

### Linear Regression From Scratch

In [62]:
feature_array = np.array([[2104, 5, 1, 45], 
                          [1416, 3, 2, 40], 
                          [852, 2, 1, 35]])

target_array = np.array([460, 232, 178])

print(feature_array.shape)
print(target_array.shape)

(3, 4)
(3,)


In [63]:
weight_arr = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
weight_arr

array([  0.39133535,  18.75376741, -53.36032453, -26.42131618])

In [ ]:
predicted_arr = []
b_init = 785.1811367994083

for i in range(feature_array.shape[0]):
    row_equation = 0
    for j in range(feature_array.shape[1]):
        row_equation += weight_arr[j] * feature_array[i, j] + b_init
    predicted_arr.append(row_equation)

predicted_arr = np.array(predicted_arr)
predicted_arr

array([2815.54340802, 2587.54340877, 2533.54340939])

In [65]:
predicted_arr

array([2815.54340802, 2587.54340877, 2533.54340939])

In [66]:
def cost_function(number_of_rows, predicted_arr, target_array):
    summation = 0
    for i in range(predicted_arr.shape[0]):
        summation += (predicted_arr[i] - target_array[i]) ** 2
    mean_squared_error = summation / (2 * number_of_rows)
    return mean_squared_error

print(cost_function(feature_array.shape[0], predicted_arr, target_array))

2774292.3751922455


In [90]:
def gradient_descent(feature_array, weight_arr, predicted_arr, target_array, number_of_rows):
    learning_rate = 5.0e-7
    updated_weights = []

    for i in range(feature_array.shape[1]):
        old_weight = weight_arr[i]
        error_summation = 0
        for j in range(number_of_rows):
            error = predicted_arr[j] - target_array[j]
            error_summation += error * feature_array[j][i]
        new_weight = old_weight - learning_rate * (error_summation / number_of_rows)
        updated_weights.append(new_weight)
    return updated_weights

In [91]:
gradient_descent(feature_array, weight_arr, predicted_arr, target_array, feature_array.shape[0])

[np.float64(-1.3250706136803883),
 np.float64(18.749841504319136),
 np.float64(-53.36189489227249),
 np.float64(-26.468427048173346)]